// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: "AIzaSyBKyDqoUxjYins1fpNj0VfvRkdRg_zFx_Y",
      appId: "1:510872836909:android:952f494b6bd2d5476cd1a4",
      messagingSenderId: "510872836909",
      projectId: "sudoku-game-4f461",
    );
  }
}
